[build]
  command = "npm run build"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Captura de formulários estáticos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
